usedurablestore = true
durablestorefolder = "/app/data"

msgport = 3005
rpcport = 4005
guiport = 5005

# State Channel Public Address: 0xA72DBe31224b824c438606196bE5857C6bE4cB32
pk = ""

# Chain Public Address: 0xB62da17fab129AD3DF8858B7B1a834e570b8eead
chainpk = ""

naaddress = "0xe1790ea824035184a3bf344e087fb61744992545"
vpaaddress = "0x95EfacCb38106C249F5ddC25b71677d5aF6d31A0"
caaddress = "0xe1790ea824035184a3bf344e087fb61744992545"

# RPC provider docs: https://lotus.filecoin.io/lotus/developers/glif-nodes/#testnet-endpoint
chainurl = "wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0"
chainstartblock = 915929
chainauthtoken = ""

bootpeers = "/ip4/67.207.88.72/tcp/3005/p2p/16Uiu2HAmDQj9XnHPD1d4GzS1K3DhmM5Z1cSGLfVTwVcNVdEsAN3Q"

tlscertfilepath = "/app/certs/live/brad-node.statechannels.org/fullchain.pem"
tlskeyfilepath = "/app/certs/live/brad-node.statechannels.org/privkey.pem"
