usedurablestore = true
durablestorefolder = "/app/data"

msgport = 3005
rpcport = 4005
guiport = 5005

# State Channel Public Address: 0x89825D58A7E2C198a06125be9CD0631317f9A07B
pk = ""

# Chain Public Address: 0x16e43DDc5FE417046Da7A0C469cCD4DE6b4764fA
chainpk = ""

naaddress = "0xe1790ea824035184a3bf344e087fb61744992545"
vpaaddress = "0x95EfacCb38106C249F5ddC25b71677d5aF6d31A0"
caaddress = "0xe1790ea824035184a3bf344e087fb61744992545"

# RPC provider docs: https://lotus.filecoin.io/lotus/developers/glif-nodes/#testnet-endpoint
chainurl = "wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0"
chainstartblock = 950307
chainauthtoken = ""

bootpeers = ""

tlscertfilepath = "/app/certs/live/iris-node.statechannels.org/fullchain.pem"
tlskeyfilepath = "/app/certs/live/iris-node.statechannels.org/privkey.pem"
