usedurablestore = true

msgport = 3005
rpcport = 4005
guiport = 5005

# State Channel Public Address: 0x89825D58A7E2C198a06125be9CD0631317f9A07B
pk = ""

# Chain Public Address: 0x16e43DDc5FE417046Da7A0C469cCD4DE6b4764fA
chainpk = ""

naaddress = "0x86dbCA138C8aF6f9710d17F892bA788e87BeF000"
vpaaddress = "0x9B955E99c325Be47e4De330F90d36D2E3D4778a9"
caaddress = "0xC0FA32D0ca8067C9B5b4471Eb41299537E7B6a33"

# RPC provider docs: https://lotus.filecoin.io/lotus/developers/glif-nodes/#testnet-endpoint
chainurl = "wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0"
chainauthtoken = ""

bootpeers = ""
usemdns = false
