usedurablestore = true

msgport = 3005
rpcport = 4005
guiport = 5005

# State Channel Public Address: 0x5b5d1f073540957743948eFF8d9777e6887F8b01
pk = ""

# Chain Public Address: 0x929adEcB790Eb4c8D371091475f0a824702ca1ef
chainpk = ""

naaddress = "0x86dbCA138C8aF6f9710d17F892bA788e87BeF000"
vpaaddress = "0x9B955E99c325Be47e4De330F90d36D2E3D4778a9"
caaddress = "0xC0FA32D0ca8067C9B5b4471Eb41299537E7B6a33"

# RPC provider docs: https://lotus.filecoin.io/lotus/developers/glif-nodes/#testnet-endpoint
chainurl = "wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0"
chainauthtoken = ""

bootpeers = "/ip4/67.207.88.72/tcp/3005/p2p/16Uiu2HAmHQe7ej1swi9ghLwCi5jdSxLpGP3weBaE7j5ixBf5Hbzx"
usemdns = false
