name: Check Links in MD files
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
